prepare_ruby_packages: Give better instructions to the user, when the data directory is not found

diff --git a/prepare_ruby_packages b/prepare_ruby_packages
--- a/prepare_ruby_packages
+++ b/prepare_ruby_packages
@@ -87,7 +87,7 @@ function notify_build_dir {
 
 function check_data_directory {
   if [[ ! -d $c_data_directory ]]; then
-    >&2 echo "Data directory '$c_data_directory' not found!"
+    >&2 echo "Data directory '$c_data_directory' not found! Please create it with permissions for the current user."
     exit 1
   fi
 }
